# Startup
source ~/zsh/startup.zsh

# Customize to your needs...
# Paths
source ~/zsh/paths.zsh

# Aliases
source ~/zsh/aliases.zsh

# Functions
source ~/zsh/functions.zsh

# Programs
source ~/zsh/programs.zsh
