# Startup
source ~/zsh/startup.zsh

# Customize to your needs...
# Paths
source ~/zsh/paths.zsh

# Aliases
source ~/zsh/aliases.zsh

# Functions
source ~/zsh/functions.zsh

# Programs
source ~/zsh/programs.zsh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
