-- vim.opt.nowrap = true           -- Sets wrapping to off after the linelength
-- vim.opt.sidescroll = 5
-- vim.opt.sidescrolloff = 2
-- vim.opt.colorcolumn = 90        -- The line length in python
-- 
-- vim.opt.tabstop = 4             -- number of visual spaces per TAB
-- vim.opt.softtabstop = 4         -- number of spaces in tab when editing
-- vim.opt.shiftwidth = 4          -- number of spaces to use for autoindent
-- vim.opt.expandtab = true        -- expand tab to spaces so that tabs are spaces
-- vim.opt.colorcolumn = "90"      -- Sets the colorcolumn at 90 characters
-- 
